#+title: Geoff's Emacs Config
#+language: en
#+STARTUP: fold

This is my personal [[https://www.gnu.org/gnu/incorrect-quotation.en.html][GNU]] Emacs configuration.  Originally re-created on [2026-03-27 Fri], this is an opportunity to review/redo my crusty old config that I had not meaningfully touched for about a decade.

Haphazardly thrown together from various sources. Notable inspiration, in no particular order, are linked below.  I am likely unfairly omitting some major influences (or straight up copypastas) due to the forgetfulness of flesh memory.

[[https://github.com/danielmai/.emacs.d][Daniel Mai]]
[[https://sachachua.com/dotemacs/index.html][Sacha Chua]]
[[https://www.masteringemacs.org][Mastering Emacs]]
[[https://www.newartisans.com][John Wiegley]]
[[https://howardism.org][Howard Abrams]]
[[https://www.emacswiki.org][EmacsWiki]]

_NOTE:_ Do *NOT* blindly use this config.  I will provide no support.

#+begin_src emacs-lisp
  ;;; -*- lexical-binding: t -*-
#+end_src

* First Things First

Save the annoying customization barf elsewhere.

#+begin_src emacs-lisp
  (setq custom-file (concat user-emacs-directory "custom.el"))
  (if (file-exists-p custom-file)
      (load custom-file))
#+end_src

Free up screen real estate.

#+begin_src emacs-lisp
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
#+end_src

Ask before closing.

#+begin_src emacs-lisp
  (setq confirm-kill-emacs 'y-or-n-p)
#+end_src

** Operating system specific changes

*** Linux

#+begin_src emacs-lisp
  ;;todo
#+end_src

*** macOS

#+begin_src emacs-lisp
  (if (eq system-type 'darwin)
      (org-babel-load-file "~/.emacs.d/mac-specific.org"))
#+end_src

*** Windows

#+begin_src emacs-lisp
  ;;todo
  ;; Emacs on Windows is so damn bad it is probably best to still run it under Linux with WSL?

  ;;Set the default directory so that we are not pointing at the location of =runemacs.exe= when trying to open a file the first time.
  (if (eq system-type 'windows-nt)
      (cd (concat "c:/Users/" user-login-name "/Documents/")))
#+end_src

** Sane Defaults

Mostly stolen from [[https://sanemacs.com/sanemacs.el][Sanemacs]].

#+begin_src emacs-lisp
  ;;; Useful Defaults
  (setq inhibit-startup-screen t)           ; Disable startup screen
  (setq initial-scratch-message "")         ; Make *scratch* buffer blank
  (fset 'yes-or-no-p 'y-or-n-p)             ; y-or-n-p makes answering questions faster
  (show-paren-mode 1)                       ; Show closing parens by default
  (delete-selection-mode 1)                 ; Selected text will be overwritten when you start typing
  (global-auto-revert-mode t)               ; Auto-update buffer if file has changed on disk
  (add-hook 'before-save-hook
            'delete-trailing-whitespace)    ; Delete trailing whitespace on save
#+end_src

For line numbers:

#+begin_src emacs-lisp
  (setq linum-format "%4d ")                ; Line number format

  ;; Show line numbers in programming modes
  (add-hook 'prog-mode-hook
            (if (or
                                          ; If linum-mode doesn't exist...
                 (not (fboundp 'linum-mode))
                                          ; ...or Emacs has display-line-numbers-mode capability
                 (and (fboundp 'display-line-numbers-mode) (display-graphic-p)))
                                          ; ...then use display-line-numbers-mode!
                'display-line-numbers-mode
                                          ; Otherwise, use linum-mode
              'linum-mode))

  (global-display-line-numbers-mode)
#+end_src

Other [[https://sanemacs.com/sanemacs.el][Sanemacs]] junk.

#+begin_src emacs-lisp
  (defun sanemacs/backward-kill-word ()
    (interactive "*")
    (push-mark)
    (backward-word)
    (delete-region (point) (mark)))

  ;;; Keybindings
                                          ;(global-set-key [mouse-3] 'mouse-popup-menubar-stuff)          ; Gives right-click a context menu
                                          ;(global-set-key (kbd "C->") 'indent-rigidly-right-to-tab-stop) ; Indent selection by one tab length
                                          ;(global-set-key (kbd "C-<") 'indent-rigidly-left-to-tab-stop)  ; De-indent selection by one tab length
  (global-set-key (kbd "M-DEL") 'sanemacs/backward-kill-word)    ; Kill word without copying it to your clipboard
  (global-set-key (kbd "C-DEL") 'sanemacs/backward-kill-word)    ; Kill word without copying it to your clipboard

  ;;; Put Emacs auto-save and backup files to /tmp/ or C:/Temp/
  (unless (eq system-type 'darwin) ;; This fucks up Magit for macOS? 🤔
    (defconst emacs-tmp-dir (expand-file-name (format "emacs%d" (user-uid)) temporary-file-directory)))

  (setq
   backup-by-copying t                                        ; Avoid symlinks
   delete-old-versions t
   kept-new-versions 6
   kept-old-versions 2
   version-control t
   auto-save-list-file-prefix emacs-tmp-dir
   auto-save-file-name-transforms `((".*" ,emacs-tmp-dir t))  ; Change autosave dir to tmp
   backup-directory-alist `((".*" . ,emacs-tmp-dir)))

  ;;; Lockfiles unfortunately cause more pain than benefit
  (setq create-lockfiles nil)
#+end_src

Stolen from [[https://github.com/magnars/.emacs.d/blob/master/settings/sane-defaults.el][Magnar Sveen]].

#+begin_src emacs-lisp
  ;; Also auto refresh dired, but be quiet about it
  (setq global-auto-revert-non-file-buffers t)
  (setq auto-revert-verbose nil)

  ;; Show keystrokes in progress
  (setq echo-keystrokes 0.1)

  ;; Move files to trash when deleting
  (setq delete-by-moving-to-trash t)

  ;; Real emacs knights don't use shift to mark things
  (setq shift-select-mode nil)

  ;; UTF-8 please
  (setq locale-coding-system 'utf-8) ; pretty
  (set-terminal-coding-system 'utf-8) ; pretty
  (set-keyboard-coding-system 'utf-8) ; pretty
  (set-selection-coding-system 'utf-8) ; please
  (prefer-coding-system 'utf-8) ; with sugar on top

  ;; Always display line and column numbers
  (setq line-number-mode t)
  (setq column-number-mode t)

  ;; Lines should be 80 characters wide, not 72
  (setq fill-column 80)

  ;; Save a list of recent files visited. (open recent file with C-x f)
  (recentf-mode 1)
  (setq recentf-max-saved-items 100) ;; just 20 is too recent

  ;; Save minibuffer history
  (savehist-mode 1)
  (setq history-length 1000)

  ;; Undo/redo window configuration with C-c <left>/<right>
  (winner-mode 1)

  ;; Never insert tabs
  (set-default 'indent-tabs-mode nil)

  ;; Show me empty lines after buffer end
  (set-default 'indicate-empty-lines t)

  ;; Easily navigate sillycased words
  (global-subword-mode 1)

  ;; Don't break lines for me, please TODO
  (setq-default truncate-lines t)

  ;; Keep cursor away from edges when scrolling up/down
                                          ;(require 'smooth-scrolling) ;; doesn't work anymore?
  (pixel-scroll-precision-mode 1)


  ;; Allow recursive minibuffers
  (setq enable-recursive-minibuffers t)

  ;; org-mode: Don't ruin S-arrow to switch windows please (use M-+ and M-- instead to toggle)
  (setq org-replace-disputed-keys t)

  ;; Represent undo-history as an actual tree (visualize with C-x u)
                                          ;(setq undo-tree-mode-lighter "")
                                          ;(require 'undo-tree)
                                          ;(global-undo-tree-mode)

  ;; Sentences do not need double spaces to end. Period.
  (set-default 'sentence-end-double-space nil)

  ;; 80 chars is a good width.
  (set-default 'fill-column 80)

  ;; Add parts of each file's directory to the buffer name if not unique
  (require 'uniquify)
  (setq uniquify-buffer-name-style 'forward)

  ;; A saner ediff
  (setq ediff-diff-options "-w")
  (setq ediff-split-window-function 'split-window-horizontally)
  (setq ediff-window-setup-function 'ediff-setup-windows-plain)

  ;; Nic says eval-expression-print-level needs to be set to nil (turned off) so
  ;; that you can always see what's happening. Nic is wrong.
  (setq eval-expression-print-level 100)

  ;; When popping the mark, continue popping until the cursor actually moves
  ;; Also, if the last command was a copy - skip past all the expand-region cruft.
  (defadvice pop-to-mark-command (around ensure-new-position activate)
    (let ((p (point)))
      (when (eq last-command 'save-region-or-current-line)
        ad-do-it
        ad-do-it
        ad-do-it)
      (dotimes (i 10)
        (when (= p (point)) ad-do-it))))

  (setq set-mark-command-repeat-pop t)

  ;; Offer to create parent directories if they do not exist
  ;; http://iqbalansari.github.io/blog/2014/12/07/automatically-create-parent-directories-on-visiting-a-new-file-in-emacs/
  (defun my-create-non-existent-directory ()
    (let ((parent-directory (file-name-directory buffer-file-name)))
      (when (and (not (file-exists-p parent-directory))
                 (y-or-n-p (format "Directory `%s' does not exist! Create it?" parent-directory)))
        (make-directory parent-directory t))))

  (add-to-list 'find-file-not-found-functions 'my-create-non-existent-directory)
#+end_src

Use normal order of operations in =quick-calc= and elsewhere.

#+BEGIN_SRC emacs-lisp
  (setq-default calc-multiplication-has-precedence nil)
#+END_SRC

Functions to sort words or symbols per [[https://www.emacswiki.org/emacs/SortWords][EmacsWiki]].

#+begin_src emacs-lisp
  (defun sort-words (reverse beg end)
    "Sort words in region alphabetically, in REVERSE if negative.
      Prefixed with negative \\[universal-argument], sorts in reverse.

      The variable `sort-fold-case' determines whether alphabetic case
      affects the sort order.

      See `sort-regexp-fields'."
    (interactive "*P\nr")
    (sort-regexp-fields reverse "\\w+" "\\&" beg end))

  (defun sort-symbols (reverse beg end)
    "Sort symbols in region alphabetically, in REVERSE if negative.
      See `sort-words'."
    (interactive "*P\nr")
    (sort-regexp-fields reverse "\\(\\sw\\|\\s_\\)+" "\\&" beg end))
#+end_src

* Theming

Zenburn is easy on the eyes.

#+begin_src emacs-lisp
  (use-package zenburn-theme
    :config
    (load-theme 'zenburn t))
#+end_src

Other related UI preferences.

#+begin_src emacs-lisp
  (set-frame-font "Hack 14" nil t);;TODO should this be different depending on the computer/screen?
  (set-cursor-color "red")
  (blink-cursor-mode 0)
  (set-face-attribute 'region nil :background "white smoke" :foreground "black")
#+end_src

Show tabs with a lavender background.

#+begin_src emacs-lisp
  (defface g/tab-face
    '((t (:background "lavender")))
    "Used for highlighting tabs.")

  (defvar g/tab-keyword
    '(("\t" . 'g/tab-face)))

  (dolist (hook '(text-mode-hook prog-mode-hook))
    (add-hook hook
              (lambda () (font-lock-add-keywords nil g/tab-keyword))))
#+end_src

Flash the mode line instead of beeping at me.

#+begin_src emacs-lisp
  (setq visible-bell nil
        ring-bell-function 'flash-mode-line)
  (defun flash-mode-line ()
    (invert-face 'mode-line)
    (run-with-timer 0.1 nil #'invert-face 'mode-line))
                                          ;TODO possible to also invert the mode mode-line-buffer-id foreground only?
#+end_src

Toggle highlighting of the current line (Hl-Line mode).

#+begin_src emacs-lisp
  (require 'hl-line)
  (add-hook 'prog-mode-hook #'hl-line-mode)
  (add-hook 'text-mode-hook #'hl-line-mode)
  (set-face-attribute 'hl-line nil :background "gray21")
#+end_src

* Navigation/commands
** Ido

#+begin_src emacs-lisp
  (setq ido-enable-flex-matching t)
  (setq ido-everywhere t)
  (ido-mode 1)
  (setq ido-use-filename-at-point 'guess)
  (setq ido-create-new-buffer 'always)
  (setq-default confirm-nonexistent-file-or-buffer nil)
  ;;(setq ido-file-extensions-order '(".org" ".txt" ".py" ".emacs" ".xml" ".el" ".ini" ".cfg" ".cnf"))

  (use-package ido-vertical-mode
    :config
    (ido-vertical-mode 1)
    (setq ido-vertical-define-keys 'C-n-and-C-p-only))
#+end_src

flx-ido

#+begin_src emacs-lisp
  (use-package flx-ido
    :config
    (flx-ido-mode 1)
    ;; disable ido faces to see flx highlights.
    (setq ido-enable-flex-matching t)
    (setq ido-use-faces nil))
#+end_src

** Smex

TODO bad form?
#+begin_src emacs-lisp
  (use-package smex
    :config
    (smex-initialize)
    (global-set-key (kbd "M-x") 'smex)
    (global-set-key (kbd "M-X") 'smex-major-mode-commands)
    ;; This is your old M-x.
    (global-set-key (kbd "C-c C-c M-x") 'execute-extended-command))
#+end_src

** Source Control

Magit is the killer app!

#+begin_src emacs-lisp
  (use-package magit
    :bind ("C-c g" . magit-status)
    :config
    (setq magit-display-buffer-function #'magit-display-buffer-fullframe-status-v1))
#+end_src

GitGutter

#+begin_src emacs-lisp
  (use-package git-gutter)
  (use-package fringe-helper)
  (use-package git-gutter-fringe
    :config
    (global-git-gutter-mode +1)

    (set-face-foreground 'git-gutter-fr:modified "yellow")
    (set-face-foreground 'git-gutter-fr:added    "green")
    (set-face-foreground 'git-gutter-fr:deleted  "red"))
#+end_src

* Org Mode

Add structure template shortcuts.  Like =< s Tab= to insert a code block which is used all over this file for example.

#+begin_src emacs-lisp
  (require 'org-tempo)
#+end_src

I find it distracting to have syntax highlighting in source blocks tbh.

#+begin_src emacs-lisp
  (setq org-src-fontify-natively nil)
  (set-face-attribute 'org-block nil :weight 'bold)
#+end_src

Indent based on outline structure and use visual lines.

#+begin_src emacs-lisp
  (setq org-startup-indented t)
  (add-hook 'org-mode-hook #'visual-line-mode)
#+end_src

Make the bullets pretty.

#+begin_src emacs-lisp
  ;;TODO this is bad form... improve is this is loaded only when needed?
  ;;TODO replace with org-superstar?
  (use-package org-bullets
    :config
    (setq inhibit-compacting-font-caches t)
    (add-hook 'org-mode-hook 'org-bullets-mode))
#+end_src

Change the ellipsis to an arrow (thanks [[https://endlessparentheses.com/changing-the-org-mode-ellipsis.html][Endless Parentheses]]).

#+begin_src emacs-lisp
  (setq org-ellipsis "⤵")
  ;; For whatever reason, customizing the ellipsis changes the font face to look like a link.
  (set-face-attribute 'org-ellipsis nil :foreground nil :underline nil)
#+end_src

TODO variable width font

** Faces

Make source/quote blocks stand out more.

#+begin_src emacs-lisp
  (dolist (face '(org-block-begin-line org-block org-block-end-line org-quote))
    (set-face-attribute face nil
                        :background "gray15"
                        :extend t))
#+end_src

Make todo/done colors more pronounced.

#+begin_src emacs-lisp
  (set-face-attribute 'org-todo nil :foreground "red")
  (set-face-attribute 'org-done nil :foreground "green")
  (set-face-attribute 'org-headline-done nil :foreground nil)
#+end_src

*** TODO test
*** DONE test

* Syntax and spell checking

#+begin_src emacs-lisp
  (use-package flycheck
    :ensure t
    :config
    (add-hook 'after-init-hook #'global-flycheck-mode))
#+end_src

Make sure to install some kind of spell checker (like =aspell=).

#+begin_src emacs-lisp
  (add-hook 'text-mode-hook 'flyspell-mode)
  (add-hook 'prog-mode-hook 'flyspell-prog-mode)
#+end_src

Indent buffer on save.

#+BEGIN_SRC emacs-lisp
  (add-hook 'before-save-hook (lambda ()
                                (indent-region (point-min) (point-max))))
#+END_SRC

* TODO Other Packages
** auto-sudoedit

#+begin_src emacs-lisp
  (use-package auto-sudoedit
    :config
    (auto-sudoedit-mode 1))
#+end_src

** company

COMPlete ANYthing.

#+begin_src emacs-lisp
  (use-package company
    :hook (after-init . global-company-mode)
    :config
    (setq company-idle-delay 0.5))

  ;; TODO more sub-packages or config necessary?
  (use-package company-posframe
    :init
    (company-posframe-mode 1))
#+end_src
** expand-region

#+begin_src emacs-lisp
  (use-package expand-region
    :bind ("C-=" . er/expand-region))
#+end_src

** mixed-pitch

#+begin_src emacs-lisp
  (use-package mixed-pitch
    :hook (org-mode . mixed-pitch-mode))
#+end_src

** move-text

#+begin_src emacs-lisp
  (use-package move-text
    :config
    (move-text-default-bindings)

    ;; Indent after moving
    (defun indent-region-advice (&rest ignored)
      (let ((deactivate deactivate-mark))
        (if (region-active-p)
            (indent-region (region-beginning) (region-end))
          (indent-region (line-beginning-position) (line-end-position)))
        (setq deactivate-mark deactivate)))

    (advice-add 'move-text-up :after 'indent-region-advice)
    (advice-add 'move-text-down :after 'indent-region-advice))
#+end_src

** TODO figure out what is the best multi-cursor package nowadays

** nyan-mode

#+begin_src emacs-lisp
  (use-package nyan-mode
    :init
    (setq nyan-bar-length 16)
    :config
    (nyan-mode 1))
#+end_src

** powershell

#+begin_src emacs-lisp
  (use-package powershell)
#+end_src

** rainbow-delimiters


#+begin_src emacs-lisp
  (use-package rainbow-delimiters
    :hook prog-mode-hook)
#+end_src

** restart-emacs

#+begin_src emacs-lisp
  (use-package restart-emacs)
#+end_src

** smartparens

#+begin_src emacs-lisp
  (use-package smartparens
    :ensure smartparens  ;; install the package
    :hook (prog-mode text-mode markdown-mode) ;; add `smartparens-mode` to these hooks
    :config
    ;; load default config
    (require 'smartparens-config))
#+end_src

** which-key

This is pre-installed with Emacs now?

#+begin_src emacs-lisp
  (which-key-mode)
#+end_src

* Finishing Touches

Make full screen with 2 "windows".

#+begin_src emacs-lisp
  (add-to-list 'initial-frame-alist '(fullscreen . maximized))
  (split-window-right)
#+end_src

Disable the =kill-sentence= key chord because I accidentally hit this all the time.  /#JustDvorakThings/

#+begin_src emacs-lisp
  (unbind-key "M-k")
#+end_src

** Private settings

#+begin_src emacs-lisp
                                          ;(load "path/to/private.el" :noerror)
#+end_src
